packages:
  - packages/core
  - packages/plugins/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  koffi: true
  node-pty: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
